### ISSUE TITLE
Build file paths are incorrect, must update

### ISSUE THREAD

**Issue by lynnlangit** [TeachingKidsProgramming/TeachingKidsProgramming.Java#17]
Build file paths in ant file in TKP src need updating to fix absolute path file reference to .jar files in project.  Until this is fixed, to 'see' the *.jar files, right click the TKP project > Properties > Java Build path > Libraries and remove the .jar files (screenshot below) and re-add with correct path using 'Add JARs...' button 
![tkp-build error](https://cloud.githubusercontent.com/assets/1609620/11611842/b729fbe6-9b96-11e5-95ae-556fd27ed79c.png)

Second build error is to remove dependency on TKP.Source.Java project. Right click the TKP project > Properties > Java Build path > Project and remove the 'required projects...' (TKP.Source.Java) - also shown in screenshot.
![tkp-build-error-1](https://cloud.githubusercontent.com/assets/1609620/11611843/c3ddedd4-9b96-11e5-9d56-a79549b79079.png)

Will update ant build file ASAP.

**Comment by jamesrcounts** [comment]
This should be fixed in 0afb3ff6a196ac6ccf30421808cbc84cc97355c3

**Comment by lynnlangit** [comment]
when I upgraded to Eclipse Mars .1 the upgrade re-wrote my basedir in the classpath.  We reverted to an earlier version of the .classpath file which used relative paths.  This fixes this bug.
