### ISSUE TITLE
TKP_Launcher.jar Fails with a message saying Eclipse not found at /Applications

### ISSUE THREAD

**Issue by mcoon1961** [TeachingKidsProgramming/TeachingKidsProgramming.Java#21]
I installed Eclipse via 'brew install Caskroom/cask/eclipse-java' and Eclipse appears to be present in my Applications folder and will run when I double click it. 

I am not sure why the validation is failing.

**Comment by mcoon1961** [comment]
I was able to continue by starting eclipse first and specifying the workspace. I did get a warning that Eclipse would update the project making it incompatible with older versions. This is similar to the issue of launcher not working when Eclipse was not in C: on windows.

**Comment by lynnlangit** [comment]
thanks for sharing - yes, this is a known limit of the TKP_launcher.jar.  Glad you got it working
