### ISSUE TITLE
Proposed installation for Mac didn't work. Solution was to install and use the newest Eclipse and JDE versions

### ISSUE THREAD

**Issue by sh1969** [TeachingKidsProgramming/TeachingKidsProgramming.Java#24]
I tried to follow the proposed installations on a MacBook Pro with macOS Mojave (V.10.14.1) and it didn't work (Eclipse Luna - linked in the description - crashed). After installation of the newest JDE (jdk-11.0.1_osx-x64_bin.dmg) and the newest Eclipse IDE for Java Developers
Version: 2018-09 (4.9.0), Build id: 20180917-1800,  OS: Mac OS X, v.10.14.1, x86_64 / cocoa
Java version: 11.0.1 - I was able to run TKP_Launcher.jar

**Comment by lynnlangit** [comment]
Thanks for taking the time to update the installation instructions - much appreciated
